version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/server
    command: yarn serve
    ports:
      - "6969:6969"
    environment:
      NODE_ENV: development
      PORT: 6969
    depends_on:
      - redis
      - mongodb
    networks:
      - local
  redis:
    image: redis:alpine
    ports:
      - "6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - local
  mongodb:
    image: mongo
    ports:
      - "27017"
    networks:
      - local
networks:
  local:
    driver: bridge
